global:
  resolve_timeout: 5m

route:
  receiver: default-receiver
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: default-receiver
    # No notification methods configured — alerts will be received but not sent anywhere.
